return {
  -- Colorschemes
  require("Emeric.plugins.tokyo"),
  require("Emeric.plugins.colors"),

  -- Core
  require("Emeric.plugins.telescope"),
  require("Emeric.plugins.lualine"),
  require("Emeric.plugins.treesitter"),
  require("Emeric.plugins.autopairs"),
  require("Emeric.plugins.comment"),
  require("Emeric.plugins.gitsigns"),
  require("Emeric.plugins.indent_blankline"),
  require("Emeric.plugins.nvim-tree"),
  require("Emeric.plugins.which-key"),
  require("Emeric.plugins.trouble"),
  require("Emeric.plugins.undotree"),
  require("Emeric.plugins.fugitive"),
  require("Emeric.plugins.hop"),
  require("Emeric.plugins.barbar"),
  require("Emeric.plugins.notify"),
  require("Emeric.plugins.zenmode"),
  require("Emeric.plugins.dashboard-nvim"),
  require("Emeric.plugins.nvim-cursorline"),
  require("Emeric.plugins.rainbow-delimiters"),
  require("Emeric.plugins.surround"),
  require("Emeric.plugins.replace-with-register"),
  require("Emeric.plugins.todo-comments"),
  require("Emeric.plugins.diffview"),
  require("Emeric.plugins.git-conflict"),
  require("Emeric.plugins.nvim-web-devicons"),
  require("Emeric.plugins.telescope-fzf-native"),
  require("Emeric.plugins.copilot-cmp"),
  require("Emeric.plugins.copilot-chat"),
  require("Emeric.plugins.luasnip"),
  require("Emeric.plugins.cmp-luasnip"),
  require("Emeric.plugins.friendly-snippets"),
  require("Emeric.plugins.neodev"),
  require("Emeric.plugins.lspsaga"),
  require("Emeric.plugins.typescript"),
  require("Emeric.plugins.null-ls"),
  require("Emeric.plugins.mason-null-ls"),
  require("Emeric.plugins.nvim-dap-python"),
  require("Emeric.plugins.nvim-dap-virtual-text"),
  require("Emeric.plugins.treesitter-playground"),
  require("Emeric.plugins.treesitter-context"),
  require("Emeric.plugins.cursorline"),
  require("Emeric.plugins.latex-live-preview"),
  require("Emeric.plugins.lazygit"),
  require("Emeric.plugins.vim-tabby"),
  require("Emeric.plugins.obsidian"),
  require("Emeric.plugins.tmux"),
  require("Emeric.plugins.img-clip"),
  require("Emeric.plugins.precognition"),
  require("Emeric.plugins.dressing"),
  require("Emeric.plugins.render-markdown"),
  require("Emeric.plugins.multicursor"),
  require("Emeric.plugins.cmp-dictionary"),
  require("Emeric.plugins.barbecue"),
  require("Emeric.plugins.colorizer"),


  -- LSP
  require("Emeric.plugins.mason"),
  require("Emeric.plugins.lsp"),
  require("Emeric.plugins.nvim-cmp"),
  require("Emeric.plugins.lspkind"),
  require("Emeric.plugins.conform"),
  require("Emeric.plugins.lsp_lines"),
  require("Emeric.plugins.jdtls"),

  -- DAP
  require("Emeric.plugins.dap"),
  require("Emeric.plugins.dapui"),
  require("Emeric.plugins.mason-nvim-dap"),

  -- AI
  require("Emeric.plugins.copilot"),
  require("Emeric.plugins.tabby"),
  require("Emeric.plugins.gen_nvim"),
  -- require("Emeric.plugins.avante"),

  -- Other
  require("Emeric.plugins.harpoon"),
  require("Emeric.plugins.cloak"),
  require("Emeric.plugins.presence"),
  require("Emeric.plugins.lazydocker"),
  require("Emeric.plugins.refactoring"),
  require("Emeric.plugins.vimtex"),
  require("Emeric.plugins.vim-latex-live-preview"),
  require("Emeric.plugins.neorg"),
  require("Emeric.plugins.noice"),
}
